#ifndef _DRAWING_H
#define _DRAWING_H

#define ELI_BLUE 0x0007
#define ELI_PINK 0xFC9F
#define BG_COLOUR TFT_BLACK
#define BAND_COLOUR_ONE TFT_RED
#define BAND_COLOUR_TWO TFT_GREEN
#define BAND_COLOUR_THREE TFT_BLUE
#define BAND_COLOUR_FOUR TFT_YELLOW
#define BAND_COLOUR_FIVE TFT_ORANGE
#define BAND_COLOUR_SIX TFT_PURPLE



#endif